<?php include "header.php"; ?>
<div class="container text-justify">
<h5 style="line-height: 1.56; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 14pt 0pt;"><span style="font-size: 37pt; font-family: Arial; color: #454545; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">About us</span></h5>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">mammypages.com</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">An information portal targeting First-time parents; here you&rsquo;ll find all the latest expert advice covering every aspect of becoming a mum. We will guide you through each stage of pregnancy, prepare you for birth, get to grips with new motherhood and even take the tantrums out of toddlerhood</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Our Audience</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Engaged couples, nesters and new parents turn to our brands for expert guidance, fresh ideas, and a supportive community and to share the joy of experiencing life&rsquo;s greatest moments.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">mammypages.com most important objective is to award something useful for good parenting &ndash; motherhood and fatherhood. We are now making the deliciously inventive panoply of technological environment for mothers, while focusing on the surrounding society of the motherhood. This is our- mammypages.com next expeditious aspiration.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">mammypages.com is one of the largest and best web market or Internet store, which is filled with the largest scale of baby and maternity production.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15pt 0pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #808080; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">mammypages.com is accelerating furthermore uninterruptedly, facing several barriers and challenges, while helping the family circle with useful and practical advises/guidance. Anyone in the community, who seek knowledge of motherhood or parenting, could be easily grasped the comprehension of their doubted perception from our knowledge portal.</span></p>
<p>&nbsp;</p>
</div>
<?php include "footer.php"; ?>